### ISSUE TITLE
quick question on the pipe methos

### ISSUE THREAD

**Issue by tzookb** [frankdejonge/pipeline#26]
I noticed when you pipe, you must do:

``` php
$pipeline = $pipeline->pipe(WHATEVER);
```

as the pipe clones the old pipeline and returns the cloned pipeline.

Now if we have 100 pipes (just an example)

isn't it better to simply return the same pipeline and not wasting memory
on never used old pipelines that were cloned....

**Comment by GreatOwl** [comment]
@tzookb , the main concept being implemented here is called immutability. It's growing in popularity amongst object oriented communities because of its ability to simplify maintain ability of a codebase. Your comment on use of memory is a common criticism of immutability when it comes to speed, but the speed implications are minimal and this architecture pattern can actually assist in allowing your application to scale (there's more to it but this helps). 

Here's a link that covers some of the key features and criticisms of immutability in php briefly. But I encourage you to do more research as its a very important topic in modern code communities. https://www.phproundtable.com/episode/immutability-and-functional-concepts-in-php

**Comment by tzookb** [comment]
Thanks @GreatOwl ,

for your time posting that message and great content link.
