### ISSUE TITLE
Isn't process method available on PipelineInterface? It's expected to be there.

### ISSUE THREAD

**Issue by motammem** [frankdejonge/pipeline#33]

**Comment by GreatOwl** [comment]
Interesting question, the function is available on the pipeline as a public method, but it looks like it's being used by the invoke method as if it were a private method. The process function does belong to the processor interface, and doesn't belong to the pipeline really. I wouldn't say that we would want the pipelineinterface to extend or be extended by the processor interface since that could confuse people on the functionality of the processor. I think that method may have been put there for convenience and not meant to be used as part of the interface.  But this is one I would be interested to know if all my arbitrary theorizing is correct, when we get an answer.

**Comment by motammem** [comment]
According to Separation of Concerns it's good practice to separate structure from it's processor.
And to do this in the clean way we can pass structure to executor in order to process it, passing structure to processor should be done through process method ( not constructor ) to make processor stateless and reusable to process other structures as well.

In our case I suggest to remove `ProcessorInterface`  reference from `Pipeline` class and refactor `process` method on `ProcessorInterface`  to accept `PipelineInterface` and `$payload`.

**Comment by GreatOwl** [comment]
I really like this suggestion actually. Replacing the current contract of the processor to accept the pipeline and providing access to the stages on the pipeline for use in the processor.  By doing that, you don't have to know up front how you want to process the stages, that can now be done later if you want. 

Similarly, we could finally make the pipeline immutable if we wanted, as it is only an ordered collection of callables at that point. But maybe I'm hoping for too much with that.

**Comment by shadowhand** [comment]
I think the current structure is doing Dependency Inversion correctly.

**Comment by courtney-miles** [comment]
> I think the current structure is doing Dependency Inversion correctly.

In this case, perhaps the docs need to change?

This is the example from the docs.

```php
$pipeline = (new Pipeline)
    ->pipe(new TimesTwoStage)
    ->pipe(new AddOneStage);

$pipeline->process(10);
```

The issue is that `$pipeline` is an instance of `PipelineInterface` and not `Pipeline`, so it's wrong to assume there is a `process()` method that can be called.  Insightful IDEs correctly report this code as a problem.

I suspect the example should instead be the following.

```php
$pipeline = (new Pipeline)
    ->pipe(new TimesTwoStage)
    ->pipe(new AddOneStage);

$pipeline(10);
```

Otherwise, the examples should be switched around to the following:

```php
$pipeline = new Pipeline(
    null,
    (new TimesTwoStage),
    (new AddOneStage)
);

$pipeline->process(10);
```

I'm happy to submit a PR for the change if there is an agreement.
